//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Breeze.ContextProvider;
using Breeze.WebApi2;
using Oc.Carbon.DataAccess;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using System.Web.Http.Cors;



namespace Oc.Carbon.WebServices.Controllers
{
    [BreezeController]
    [EnableCors(origins: "*", headers: "*", methods: "*", exposedHeaders: "*")]
    public class SoPlatformController : ApiController
    {
        // Todo: inject via an interface rather than "new" the concrete class
        readonly PlatformRepository _repository = new PlatformRepository();

        [HttpGet]
        public string Metadata()
        {

            var metaData = _repository.Metadata;
            return metaData;
        }

        [HttpPost]
        public SaveResult SaveChanges(JObject saveBundle)
        {
             
            try
            {
                return _repository.SaveChanges(saveBundle);
            }
            catch (Exception exp)
            {

                var message = new HttpResponseMessage(HttpStatusCode.BadRequest);
                message.Content = new StringContent(exp.Message);
                throw new HttpResponseException(message);

            }
        }


        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<Attrib> Attribs()
        {
             return _repository.Attribs;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<AttribTyp> AttribTyps()
        {
             return _repository.AttribTyps;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<Audit> Audits()
        {
             return _repository.Audits;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<AuditAction> AuditActions()
        {
             return _repository.AuditActions;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<AuditCat> AuditCats()
        {
             return _repository.AuditCats;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<AuditCatAuditTyp> AuditCatAuditTyps()
        {
             return _repository.AuditCatAuditTyps;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<AuditDtl> AuditDtls()
        {
             return _repository.AuditDtls;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<AuditTyp> AuditTyps()
        {
             return _repository.AuditTyps;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<AuthItem> AuthItems()
        {
             return _repository.AuthItems;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<AuthItemAuthPerm> AuthItemAuthPerms()
        {
             return _repository.AuthItemAuthPerms;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<AuthPerm> AuthPerms()
        {
             return _repository.AuthPerms;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<AuthRol> AuthRols()
        {
             return _repository.AuthRols;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<AuthRolAuthItemAuthPerm> AuthRolAuthItemAuthPerms()
        {
             return _repository.AuthRolAuthItemAuthPerms;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<AuthRolTyp> AuthRolTyps()
        {
             return _repository.AuthRolTyps;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<Contact> Contacts()
        {
             return _repository.Contacts;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<ContactTyp> ContactTyps()
        {
             return _repository.ContactTyps;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<Country> Countries()
        {
             return _repository.Countries;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<soUpload> Docs()
        {
             return _repository.soUploads;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<Elm> Elms()
        {
             return _repository.Elms;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<ElmElm> ElmElms()
        {
             return _repository.ElmElms;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<ElmTyp> ElmTyps()
        {
             return _repository.ElmTyps;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<EntityAttributeTyp> EntityAttributeTyps()
        {
             return _repository.EntityAttributeTyps;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<EquipTyp> EquipTyps()
        {
             return _repository.EquipTyps;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<Gender> Genders()
        {
             return _repository.Genders;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<IconVisual> IconVisuals()
        {
             return _repository.IconVisuals;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<IconVisualTyp> IconVisualTyps()
        {
             return _repository.IconVisualTyps;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<LayoutTyp> LayoutTyps()
        {
             return _repository.LayoutTyps;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<Locality> Localities()
        {
             return _repository.Localities;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<Locn> Locns()
        {
             return _repository.Locns;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<LogCat> LogCats()
        {
             return _repository.LogCats;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<LogEntry> LogEntries()
        {
             return _repository.LogEntries;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<Menu> Menus()
        {
             return _repository.Menus;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<MenuItem> MenuItems()
        {
             return _repository.MenuItems;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<Mod> Mods()
        {
             return _repository.Mods;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<ModAuthRol> ModAuthRols()
        {
             return _repository.ModAuthRols;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<ModelEntity> ModelEntities()
        {
             return _repository.ModelEntities;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<ModelEntityAttribute> ModelEntityAttributes()
        {
             return _repository.ModelEntityAttributes;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<ModElm> ModElms()
        {
             return _repository.ModElms;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<ModElmElm> ModElmElms()
        {
             return _repository.ModElmElms;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<ModElmTyp> ModElmTyps()
        {
             return _repository.ModElmTyps;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<ModSetting> ModSettings()
        {
             return _repository.ModSettings;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<ModSettingValue> ModSettingValues()
        {
             return _repository.ModSettingValues;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<ModState> ModStates()
        {
             return _repository.ModStates;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<ModTyp> ModTyps()
        {
             return _repository.ModTyps;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<Org> Orgs()
        {
             return _repository.Orgs;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<OrgContact> OrgContacts()
        {
             return _repository.OrgContacts;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<OrgCust> OrgCusts()
        {
             return _repository.OrgCusts;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<OrgLocn> OrgLocns()
        {
             return _repository.OrgLocns;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<OrgNote> OrgNotes()
        {
             return _repository.OrgNotes;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<OrgOrg> OrgOrgs()
        {
             return _repository.OrgOrgs;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<OrgStatus> OrgStatus()
        {
             return _repository.OrgStatus;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<OrgStatusHist> OrgStatusHists()
        {
             return _repository.OrgStatusHists;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<OrgTyp> OrgTyps()
        {
             return _repository.OrgTyps;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<OrgTypOrgStatus> OrgTypOrgStatus()
        {
             return _repository.OrgTypOrgStatus;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<Part> Parts()
        {
             return _repository.Parts;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<PartGrp> PartGrps()
        {
             return _repository.PartGrps;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<PartGrpPart> PartGrpParts()
        {
             return _repository.PartGrpParts;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<PartIndicator> PartIndicators()
        {
             return _repository.PartIndicators;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<PartSetting> PartSettings()
        {
             return _repository.PartSettings;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<PartTyp> PartTyps()
        {
             return _repository.PartTyps;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<Per> Pers()
        {
             return _repository.Pers;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<PerNote> PerNotes()
        {
             return _repository.PerNotes;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<PersContact> PersContacts()
        {
             return _repository.PersContacts;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<PlaceHolder> PlaceHolders()
        {
             return _repository.PlaceHolders;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<Port> Ports()
        {
             return _repository.Ports;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<PortMod> PortMods()
        {
             return _repository.PortMods;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<PortModModElm> PortModModElms()
        {
             return _repository.PortModModElms;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<PortModSetting> PortModSettings()
        {
             return _repository.PortModSettings;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<PortModSettingValue> PortModSettingValues()
        {
             return _repository.PortModSettingValues;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<PortScene> PortScenes()
        {
             return _repository.PortScenes;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<PortUser> PortUsers()
        {
             return _repository.PortUsers;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<Scene> Scenes()
        {
             return _repository.Scenes;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<ScenePart> SceneParts()
        {
             return _repository.SceneParts;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<ScenePartPartSetting> ScenePartPartSettings()
        {
             return _repository.ScenePartPartSettings;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<Setting> Settings()
        {
             return _repository.Settings;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<SettingTyp> SettingTyps()
        {
             return _repository.SettingTyps;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<State> States()
        {
             return _repository.States;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<User> Users()
        {
             return _repository.Users;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<UserLoginHist> UserLoginHists()
        {
             return _repository.UserLoginHists;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<UserModAuthRol> UserModAuthRols()
        {
             return _repository.UserModAuthRols;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<WkflowDef> WkflowDefs()
        {
             return _repository.WkflowDefs;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<WkflowDefStatRea> WkflowDefStatReas()
        {
             return _repository.WkflowDefStatReas;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<WkflowDefWkflowStat> WkflowDefWkflowStats()
        {
             return _repository.WkflowDefWkflowStats;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<WkflowDefWkflowStatWkflowStat> WkflowDefWkflowStatWkflowStats()
        {
             return _repository.WkflowDefWkflowStatWkflowStats;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<WkflowInstance> WkflowInstances()
        {
             return _repository.WkflowInstances;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<WkflowInstanceDoc> WkflowInstanceDocs()
        {
             return _repository.WkflowInstanceDocs;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<WkflowStat> WkflowStats()
        {
             return _repository.WkflowStats;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<WkflowStatRea> WkflowStatReas()
        {
             return _repository.WkflowStatReas;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<WkflowStepHist> WkflowStepHists()
        {
             return _repository.WkflowStepHists;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<WkflowStepNote> WkflowStepNotes()
        {
             return _repository.WkflowStepNotes;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<WkflowTyp> WkflowTyps()
        {
             return _repository.WkflowTyps;
        }
    

        [HttpGet]
		[EnableBreezeQuery(MaxExpansionDepth = 8)]
        public IQueryable<ZipCode> ZipCodes()
        {
             return _repository.ZipCodes;
        }
    


        // Diagnostic
        [HttpGet]
        public string Ping()
        {
            return "pong";
        }

//        [HttpGet]
//       public string GenerateCode()
//        {
//            return _repository.GenerateCode();
//        }

       
    }
}

