
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oc.Carbon.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class IconVisual
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public IconVisual()
    {

        this.Genders = new HashSet<Gender>();

        this.LogCats = new HashSet<LogCat>();

        this.MenuItems = new HashSet<MenuItem>();

        this.Menus = new HashSet<Menu>();

        this.PortMods = new HashSet<PortMod>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string IconPath { get; set; }

    public string Descript { get; set; }

    public string Content { get; set; }

    public Nullable<int> IconVisualTypId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Gender> Genders { get; set; }

    public virtual IconVisualTyp IconVisualTyp { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LogCat> LogCats { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MenuItem> MenuItems { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Menu> Menus { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PortMod> PortMods { get; set; }

}

}
