
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oc.Carbon.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class LogEntry
{

    public int Id { get; set; }

    public string ErrorCode { get; set; }

    public string Message { get; set; }

    public string CreateDate { get; set; }

    public string Application { get; set; }

    public int LogCatId { get; set; }



    public virtual LogCat LogCat { get; set; }

}

}
