
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oc.Carbon.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Message
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Message()
    {

        this.MessageUsers = new HashSet<MessageUser>();

    }


    public int Id { get; set; }

    public string MessageBody { get; set; }

    public System.DateTime CreateDate { get; set; }

    public Nullable<System.DateTime> DeliveredDate { get; set; }

    public Nullable<int> WkflowInstanceId { get; set; }

    public string HeaderText { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MessageUser> MessageUsers { get; set; }

    public virtual WkflowInstance WkflowInstance { get; set; }

}

}
