

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oc.Carbon.DataAccess
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Validation;
using System.Diagnostics;


public partial class SoPlatformEntities : DbContext
{
    public SoPlatformEntities()
        : base("name=SoPlatformEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

	public virtual void Commit()
    {
        try
        {
            base.SaveChanges();
        }
        catch (DbEntityValidationException dbEx)
        {
            foreach (var validationErrors in dbEx.EntityValidationErrors)
            {
                foreach (var validationError in validationErrors.ValidationErrors)
                {
                    Trace.TraceInformation("Class: {0}, Property: {1}, Error: {2}", validationErrors.Entry.Entity.GetType().FullName,
                                    validationError.PropertyName, validationError.ErrorMessage);
                }
            }
        }
    }


    public virtual DbSet<Attrib> Attribs { get; set; }

    public virtual DbSet<AttribTyp> AttribTyps { get; set; }

    public virtual DbSet<AuditAction> AuditActions { get; set; }

    public virtual DbSet<AuditCatAuditTyp> AuditCatAuditTyps { get; set; }

    public virtual DbSet<AuditCat> AuditCats { get; set; }

    public virtual DbSet<AuditDtl> AuditDtls { get; set; }

    public virtual DbSet<Audit> Audits { get; set; }

    public virtual DbSet<AuditTyp> AuditTyps { get; set; }

    public virtual DbSet<AuthItemAuthPerm> AuthItemAuthPerms { get; set; }

    public virtual DbSet<AuthItem> AuthItems { get; set; }

    public virtual DbSet<AuthPerm> AuthPerms { get; set; }

    public virtual DbSet<AuthRolAuthItemAuthPerm> AuthRolAuthItemAuthPerms { get; set; }

    public virtual DbSet<AuthRol> AuthRols { get; set; }

    public virtual DbSet<AuthRolTyp> AuthRolTyps { get; set; }

    public virtual DbSet<Contact> Contacts { get; set; }

    public virtual DbSet<ContactTyp> ContactTyps { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<soUpload> soUploads { get; set; }

    public virtual DbSet<ElmElm> ElmElms { get; set; }

    public virtual DbSet<Elm> Elms { get; set; }

    public virtual DbSet<ElmTyp> ElmTyps { get; set; }

    public virtual DbSet<EntityAttributeTyp> EntityAttributeTyps { get; set; }

    public virtual DbSet<EquipTyp> EquipTyps { get; set; }

    public virtual DbSet<Gender> Genders { get; set; }

    public virtual DbSet<IconVisual> IconVisuals { get; set; }

    public virtual DbSet<IconVisualTyp> IconVisualTyps { get; set; }

    public virtual DbSet<LayoutTyp> LayoutTyps { get; set; }

    public virtual DbSet<Locality> Localities { get; set; }

    public virtual DbSet<Locn> Locns { get; set; }

    public virtual DbSet<LogCat> LogCats { get; set; }

    public virtual DbSet<LogEntry> LogEntries { get; set; }

    public virtual DbSet<MenuItem> MenuItems { get; set; }

    public virtual DbSet<Menu> Menus { get; set; }

    public virtual DbSet<ModAuthRol> ModAuthRols { get; set; }

    public virtual DbSet<ModelEntity> ModelEntities { get; set; }

    public virtual DbSet<ModelEntityAttribute> ModelEntityAttributes { get; set; }

    public virtual DbSet<ModElmElm> ModElmElms { get; set; }

    public virtual DbSet<ModElm> ModElms { get; set; }

    public virtual DbSet<ModElmTyp> ModElmTyps { get; set; }

    public virtual DbSet<Mod> Mods { get; set; }

    public virtual DbSet<ModSetting> ModSettings { get; set; }

    public virtual DbSet<ModSettingValue> ModSettingValues { get; set; }

    public virtual DbSet<ModState> ModStates { get; set; }

    public virtual DbSet<ModTyp> ModTyps { get; set; }

    public virtual DbSet<OrgContact> OrgContacts { get; set; }

    public virtual DbSet<OrgCust> OrgCusts { get; set; }

    public virtual DbSet<OrgLocn> OrgLocns { get; set; }

    public virtual DbSet<OrgNote> OrgNotes { get; set; }

    public virtual DbSet<OrgOrg> OrgOrgs { get; set; }

    public virtual DbSet<Org> Orgs { get; set; }

    public virtual DbSet<OrgStatus> OrgStatus { get; set; }

    public virtual DbSet<OrgStatusHist> OrgStatusHists { get; set; }

    public virtual DbSet<OrgTypOrgStatus> OrgTypOrgStatus { get; set; }

    public virtual DbSet<OrgTyp> OrgTyps { get; set; }

    public virtual DbSet<PartGrpPart> PartGrpParts { get; set; }

    public virtual DbSet<PartGrp> PartGrps { get; set; }

    public virtual DbSet<PartIndicator> PartIndicators { get; set; }

    public virtual DbSet<Part> Parts { get; set; }

    public virtual DbSet<PartSetting> PartSettings { get; set; }

    public virtual DbSet<PartTyp> PartTyps { get; set; }

    public virtual DbSet<PerNote> PerNotes { get; set; }

    public virtual DbSet<Per> Pers { get; set; }

    public virtual DbSet<PersContact> PersContacts { get; set; }

    public virtual DbSet<PlaceHolder> PlaceHolders { get; set; }

    public virtual DbSet<PortModModElm> PortModModElms { get; set; }

    public virtual DbSet<PortMod> PortMods { get; set; }

    public virtual DbSet<PortModSetting> PortModSettings { get; set; }

    public virtual DbSet<PortModSettingValue> PortModSettingValues { get; set; }

    public virtual DbSet<Port> Ports { get; set; }

    public virtual DbSet<PortScene> PortScenes { get; set; }

    public virtual DbSet<PortUser> PortUsers { get; set; }

    public virtual DbSet<ScenePartPartSetting> ScenePartPartSettings { get; set; }

    public virtual DbSet<ScenePart> SceneParts { get; set; }

    public virtual DbSet<Scene> Scenes { get; set; }

    public virtual DbSet<Setting> Settings { get; set; }

    public virtual DbSet<SettingTyp> SettingTyps { get; set; }

    public virtual DbSet<State> States { get; set; }

    public virtual DbSet<UserLoginHist> UserLoginHists { get; set; }

    public virtual DbSet<UserModAuthRol> UserModAuthRols { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<WkflowDef> WkflowDefs { get; set; }

    public virtual DbSet<WkflowDefStatRea> WkflowDefStatReas { get; set; }

    public virtual DbSet<WkflowDefWkflowStat> WkflowDefWkflowStats { get; set; }

    public virtual DbSet<WkflowDefWkflowStatWkflowStat> WkflowDefWkflowStatWkflowStats { get; set; }

    public virtual DbSet<WkflowInstanceDoc> WkflowInstanceDocs { get; set; }

    public virtual DbSet<WkflowInstance> WkflowInstances { get; set; }

    public virtual DbSet<WkflowStatRea> WkflowStatReas { get; set; }

    public virtual DbSet<WkflowStat> WkflowStats { get; set; }

    public virtual DbSet<WkflowStepHist> WkflowStepHists { get; set; }

    public virtual DbSet<WkflowStepNote> WkflowStepNotes { get; set; }

    public virtual DbSet<WkflowTyp> WkflowTyps { get; set; }

    public virtual DbSet<ZipCode> ZipCodes { get; set; }

    public virtual DbSet<OrgReseller> OrgResellers { get; set; }

    public virtual DbSet<ServicePackage> ServicePackages { get; set; }

    public virtual DbSet<FileType> FileTypes { get; set; }

    public virtual DbSet<DPWorkflow> DPWorkflows { get; set; }

    public virtual DbSet<DataElm> DataElms { get; set; }

    public virtual DbSet<OrgDocTyp> OrgDocTyps { get; set; }

    public virtual DbSet<DataElmTyp> DataElmTyps { get; set; }

    public virtual DbSet<OrgDocTypDataElm> OrgDocTypDataElms { get; set; }

    public virtual DbSet<OrgUser> OrgUsers { get; set; }

    public virtual DbSet<UserAuthRol> UserAuthRols { get; set; }

    public virtual DbSet<Package> Packages { get; set; }

    public virtual DbSet<OrgPackage> OrgPackages { get; set; }

    public virtual DbSet<MessageTemplate> MessageTemplates { get; set; }

    public virtual DbSet<DeliveryMethod> DeliveryMethods { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<MessageUser> MessageUsers { get; set; }

    public virtual DbSet<OrgPackageHist> OrgPackageHists { get; set; }

    public virtual DbSet<Holiday> Holidays { get; set; }

    public virtual DbSet<SOActivity> SOActivities { get; set; }

    public virtual DbSet<DocTypStatus> DocTypStatus { get; set; }

    public virtual DbSet<PortSettingValue> PortSettingValues { get; set; }

    public virtual DbSet<PortSetting> PortSettings { get; set; }

    public virtual DbSet<SowWkflow> SowWkflows { get; set; }

    public virtual DbSet<SowAttribute> SowAttributes { get; set; }

    public virtual DbSet<SowAttributeValueHist> SowAttributeValueHists { get; set; }

    public virtual DbSet<SowWklowSowAttribute> SowWklowSowAttributes { get; set; }

    public virtual DbSet<SowWkflowDocSetup> SowWkflowDocSetups { get; set; }

    public virtual DbSet<OrgResellerDiscHist> OrgResellerDiscHists { get; set; }

    public virtual DbSet<SOWWkflowOrgResellerDiscOverride> SOWWkflowOrgResellerDiscOverrides { get; set; }

    public virtual DbSet<Month> Months { get; set; }

    public virtual DbSet<OrgDocTypMonth> OrgDocTypMonths { get; set; }

    public virtual DbSet<SubWhiteList> SubWhiteLists { get; set; }

    public virtual DbSet<OrgMonthCommitment> OrgMonthCommitments { get; set; }

    public virtual DbSet<OrgDocTypDailyUpload> OrgDocTypDailyUploads { get; set; }

}

}

